/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CallRouteImport } from './routes/call'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamsExamIdRouteImport } from './routes/exams.$examId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdRoute = ExamsExamIdRouteImport.update({
  id: '/$examId',
  path: '/$examId',
  getParentRoute: () => ExamsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/call': typeof CallRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRouteWithChildren
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/exams/$examId': typeof ExamsExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/call': typeof CallRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRouteWithChildren
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/exams/$examId': typeof ExamsExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/call': typeof CallRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRouteWithChildren
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/exams/$examId': typeof ExamsExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/call'
    | '/dashboard'
    | '/exams'
    | '/login'
    | '/progress'
    | '/register'
    | '/settings'
    | '/admin/questions'
    | '/admin/users'
    | '/exams/$examId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/call'
    | '/dashboard'
    | '/exams'
    | '/login'
    | '/progress'
    | '/register'
    | '/settings'
    | '/admin/questions'
    | '/admin/users'
    | '/exams/$examId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/call'
    | '/dashboard'
    | '/exams'
    | '/login'
    | '/progress'
    | '/register'
    | '/settings'
    | '/admin/questions'
    | '/admin/users'
    | '/exams/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CallRoute: typeof CallRoute
  DashboardRoute: typeof DashboardRoute
  ExamsRoute: typeof ExamsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId': {
      id: '/exams/$examId'
      path: '/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof ExamsExamIdRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExamsRouteChildren {
  ExamsExamIdRoute: typeof ExamsExamIdRoute
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsExamIdRoute: ExamsExamIdRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CallRoute: CallRoute,
  DashboardRoute: DashboardRoute,
  ExamsRoute: ExamsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
